//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAGEPhotoManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RAGEPhotoManager.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à browse.
        /// </summary>
        public static string buttonBrowse {
            get {
                return ResourceManager.GetString("buttonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string buttonDelete {
            get {
                return ResourceManager.GetString("buttonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to JPEG.
        /// </summary>
        public static string buttonExportToJPEG {
            get {
                return ResourceManager.GetString("buttonExportToJPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share to social media.
        /// </summary>
        public static string buttonShareToSocialMedia {
            get {
                return ResourceManager.GetString("buttonShareToSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autosave JPEGs to folder :.
        /// </summary>
        public static string checkBoxAutosave {
            get {
                return ResourceManager.GetString("checkBoxAutosave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start with system.
        /// </summary>
        public static string checkboxStartWithSystem {
            get {
                return ResourceManager.GetString("checkboxStartWithSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ingame time.
        /// </summary>
        public static string columnHeaderIngameDate {
            get {
                return ResourceManager.GetString("columnHeaderIngameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location.
        /// </summary>
        public static string columnHeaderName {
            get {
                return ResourceManager.GetString("columnHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo.
        /// </summary>
        public static string columnHeaderPic {
            get {
                return ResourceManager.GetString("columnHeaderPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real time.
        /// </summary>
        public static string columnHeaderRealDate {
            get {
                return ResourceManager.GetString("columnHeaderRealDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General settings.
        /// </summary>
        public static string groupBoxGeneralSettings {
            get {
                return ResourceManager.GetString("groupBoxGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions.
        /// </summary>
        public static string groupBoxPhotoActions {
            get {
                return ResourceManager.GetString("groupBoxPhotoActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties.
        /// </summary>
        public static string groupBoxPhotoProperties {
            get {
                return ResourceManager.GetString("groupBoxPhotoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Social.
        /// </summary>
        public static string groupboxSocial {
            get {
                return ResourceManager.GetString("groupboxSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login:.
        /// </summary>
        public static string loginLabel {
            get {
                return ResourceManager.GetString("loginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password:.
        /// </summary>
        public static string passwordLabel {
            get {
                return ResourceManager.GetString("passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snapmatic.
        /// </summary>
        public static string snapmatic {
            get {
                return ResourceManager.GetString("snapmatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create an account.
        /// </summary>
        public static string snapmaticCreateAccount {
            get {
                return ResourceManager.GetString("snapmaticCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgot your password ?.
        /// </summary>
        public static string snapmaticForgotPassword {
            get {
                return ResourceManager.GetString("snapmaticForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RAGE Photo manager.
        /// </summary>
        public static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Submit.
        /// </summary>
        public static string submitButton {
            get {
                return ResourceManager.GetString("submitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string tabSettings {
            get {
                return ResourceManager.GetString("tabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photos.
        /// </summary>
        public static string tabTitlePhotos {
            get {
                return ResourceManager.GetString("tabTitlePhotos", resourceCulture);
            }
        }
    }
}
